import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "../components/layouts/Navbar";
import Footer from "../components/layouts/Footer";
import NextAuthprovider from "../provider/NextAuthprovider";

const poppins = Poppins(
  {
    weight: ['100', '200', '400', '500', '600', '800']
  }
)

export const metadata: Metadata = {
  title: {
    default: "Intellicode",
    template: "%s || Intellicode"
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <NextAuthprovider>
      <html lang="en">
        <body
          className={`${poppins.className} antialiased`}
        >
          <header>
            <Navbar />
          </header>
          <main>
            {children}
          </main>
          <footer>
            <Footer />
          </footer>
        </body>
      </html>
    </NextAuthprovider>
  );
}
